name: Publish website to Github Pages repo

on:
  workflow_dispatch:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
    
jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          path: source

      - name: Checkout publish repo
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.PUBLISH_REPO }}
          token: ${{ secrets.PUBLISH_REPO_TOKEN }}
          path: publish
          
      - name: Setup node
        uses: actions/setup-node@v3
      
      - name: Compile source
        run: |
          cd source/splapp
          npm install
          npm run build
          cd ../..
          cp -r source/splapp/dist/* publish/
      
      - name: Publish
        run: |
          cd publish
          date > generated.txt
          git config user.name actions
          git config user.email actions@github.com
          git add .
          git commit -m "generated"
          git push
